enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1
remove-rv-integrations-checks = true # Automatically patch shared integration checks

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/dj-tanjid/Morphe-DeVanced-Builder/blob/teejay/CONFIG.md for more detailed explanations

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# Stable Support #
# version = "auto" # 'auto', 'experimental', 'latest' or a version number
# Experimental Support #
# version = "21.28.207" # Version Supporting Miniplayer Type
# version = "experimental"
version = "auto"
dpi = "nodpi" # Options '120-640dpi', or 'nodpi'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.google.android.youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YT-Music-Morphe]
app-name = "YT Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "both" # Options 'apk', 'module', or 'both'
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
# Stable Support #
# version = "auto" # 'auto', 'experimental', 'latest' or a version number
# Experimental Support #
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Morphe"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# Stable Support #
# version = "auto" # 'auto', 'experimental', 'latest' or a version number
# Experimental Support #
# version = "2026.34.0"
dpi = "120-640dpi" # Options '120-640dpi', or 'nodpi'
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Google-Photos-De-Vanced]
app-name = "Google Photos"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
version = "auto"
# version = "auto" # 'auto', 'experimental', 'latest' or a version number
# version = "7.89.0.968035987"
build-mode = "both" # Options 'apk', 'module', or 'both'
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Facebook-De-Vanced]
app-name = "Facebook"
pkg-name = "com.facebook.katana"
patches-source = "github:RookieEnough/De-Vanced"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a"
# version = "latest"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
# version = "573.0.0.37.74"
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.facebook.katana"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Facebook-Froggo]
enabled = false
app-name = "Facebook"
pkg-name = "com.facebook.katana"
patches-source = "github:SapitoSucio/FroggoMorphePatches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Froggo"
arch = "arm64-v8a"
# version = "latest"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
# version = "573.0.0.37.74"
build-mode = "apk"
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Block Facebook Story ads (573)' \
    """
excluded-patches = """\
    'Block Facebook Auto Refresh' \
    """
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.facebook.katana"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Facebook-Messenger-De-Vanced]
enabled = false
app-name = "Facebook Messenger"
pkg-name = "com.facebook.orca"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "De-Vanced"
arch = "arm64-v8a"
version = "latest" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.facebook.orca"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Facebook-Messenger-Rushi]
enabled = false
app-name = "Facebook Messenger"
pkg-name = "com.facebook.orca"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
excluded-patches = """\
    'Change package name' \
    """
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.facebook.orca"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Threads-Chiggi]
enabled = false
app-name = "Threads"
pkg-name = "com.instagram.barcelona"
patches-source = "github:durgesh0505/chiggi_morphe_patches"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Chiggi"
arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.instagram.barcelona"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
uptodown-dlurl = "https://threads.en.uptodown.com/android"

[Twitter-Piko]
app-name = "Twitter"
patches-source = "github:crimera/piko"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# version = "latest" # 'auto', 'experimental', 'latest' or a version number
version = "auto"
include-stock = "split" # Options 'split', 'merged', or 'disable'
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.twitter.android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[X-Piko]
enabled = false
app-name = "X"
patches-source = "github:crimera/piko"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# version = "latest" # 'auto', 'experimental', 'latest' or a version number
version = "auto"
include-stock = "split" # Options 'split', 'merged', or 'disable'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'Dynamic color' \
    'Browse tweet object' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.twitter.android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitter-Piko-NewX]
enabled = false
app-name = "Twitter"
patches-source = "github:crimera/piko-newx"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Piko-NewX"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# version = "latest" # 'auto', 'experimental', 'latest' or a version number
version = "auto"
include-stock = "split" # Options 'split', 'merged', or 'disable'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'NewX: Restore Twitter branding' \
    'NewX: Browse tweet object' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.twitter.android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[X-Piko-NewX]
enabled = false
app-name = "X"
patches-source = "github:crimera/piko-newx"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Piko-NewX"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# version = "latest" # 'auto', 'experimental', 'latest' or a version number
version = "auto"
include-stock = "split" # Options 'split', 'merged', or 'disable'
patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
included-patches = """\
    'NewX: Browse tweet object' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.twitter.android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Instagram-Piko]
app-name = "Instagram"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
rv-brand = "Piko"
build-mode = "apk" # Options 'apk', 'module', or 'both'
# version = "latest"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
# version = "439.0.0.37.89"
arch = "arm64-v8a" # Options 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64', or 'universal'
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
# github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
github-dlurl = "https://github.com/dj-tanjid/AppRepo/releases/tag/com.instagram.android"

[1-1-1-1-Rushi]
enabled = false
app-name = "1.1.1.1"
pkg-name = "com.cloudflare.onedotonedotonedotone"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
# arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"

[Proton-VPN-Rushi]
enabled = false
app-name = "Proton VPN"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
# arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"

[Windscribe-VPN-Rushi]
enabled = false
app-name = "Windscribe VPN"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
# arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-vpn"
uptodown-dlurl = "https://windscribe.en.uptodown.com/android"

[TeraBox-Rushi]
enabled = false
app-name = "TeraBox"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/flextech-inc/terabox-cloud-storage-cloud-backup-data-backup"
uptodown-dlurl = "https://terabox.en.uptodown.com/android"

[Speedtest-by-Ookla-Rushi]
enabled = false
app-name = "Speedtest by Ookla"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
arch = "both"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"

[Send-Files-To-TV-Rushi]
enabled = false
app-name = "Send Files To TV"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
arch = "all"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/yablio/send-files-to-tv/"
uptodown-dlurl = "https://send-files-to-tv.en.uptodown.com/android"

[APKMirror-Installer-Rushi]
enabled = false
app-name = "APKMirror Installer"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
arch = "both"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/apkmirror/apkmirror-installer-official/"

[Bluetooth-Keyboard-Mouse-Rushi]
enabled = false
app-name = "Bluetooth Keyboard & Mouse"
patches-source = "github:rushiranpise/morphe-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Rushi"
arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
apkmirror-dlurl = "https://www.apkmirror.com/apk/appground-io/bluetooth-keyboard-mouse-2/"
uptodown-dlurl = "https://bluetooth-keyboard-and-mouse.en.uptodown.com/android"

[PokeRaid-DanielTheManiel]
enabled = false
app-name = "PokeRaid - for Pokémon GO Raid"
patches-source = ["github:Dan1elTheMan1el/Morphe-Patches", "github:Nai64/Nai64Patches"]
patches-version = ["dev", "latest"]
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "DanielTheManiel"
arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pyde-technologies-ltd/pokeraid-worldwide-remote-raids/"
uptodown-dlurl = "https://pokeraid-worldwide-remote-ra.en.uptodown.com/android"

[Gboard-Jason]
enabled = false
app-name = "Gboard"
patches-source = "github:jasonwu1994/Gboard-patches"
cli-source = "github:MorpheApp/morphe-desktop"
rv-brand = "Jason"
arch = "arm64-v8a"
version = "auto" # 'auto', 'experimental', 'latest' or a version number
build-mode = "both"
# patches-version = "dev" # Options 'latest', 'dev', or A specific version tag
excluded-patches = """\
    'Package Rename' \
    'Zhuyin Bottom Row Key Sizes' \
    'Zhuyin Quick Traditional/Simplified Toggle' \
    'Zhuyin Slide Input' \
    """
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
